[package]
name = "rust-zee"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "0.7.0"
rand = "0.8.4"
rocket = "0.5.0-rc.2"
serde_json = "1.0.87"
serde = "1.0.147"